### ISSUE TITLE
ProductThumbnail에서 price 자료형 확인요망

### ISSUE THREAD

**Issue by aeuna** [akalswl14/stylebox_server#1]
- [x] relatedProduct의 price는 string, mainProduct의 price는 num으로 반환되는것같습니다. 현재 대응은 해두었으나 확인이 필요합니다.

**Comment by akalswl14** [comment]
김지완 대표님 컨펌 후에 앱 API 서버에 반영해야함. 반영 여부 확인을 위해 반영 후에 이슈 클로즈 할예정.
