### ISSUE TITLE
검색 방식 변경에 따른 DB, API 변경

### ISSUE THREAD

**Issue by akalswl14** [akalswl14/stylebox_server#15]
### 내용
- 대소문자 구분 없이 중간부터 검색되게 하기 위해 변경이 필요함

### 변경사항
- 필요한 항목에 대해, 소문자로만 이루어진 string을 저장하는 필드를 추가하도록 DB를 수정함
- DB 변경에 따른 API 변경
- 중간 내용 검색과 대소문자 비구분하여 검색하도록 API 변경

**Comment by akalswl14** [comment]
@aeuna 최종적으로 체크하시고 문제 없으면 이슈 닫아주세요~

**Comment by aeuna** [comment]
검색 확인 완료 다 작동합니다
