### ISSUE TITLE
getShops(..., isClass: true)일 경우 샵 리스트 반환 오류

### ISSUE THREAD

**Issue by loiu87** [akalswl14/stylebox_server#46]
### 개요
getShops 인자에 isClass가 true일 경우, tagId에 관계없이 모든 shop을 반환

#### 입력
> {
  getShops(tagId:154,isClass: true, classId: 29){
    totalShopNum
  }
}

#### 기대
> "getShops": {
    "totalShopNum": 22
    }
#### 실제 결과
> "getShops": {
      "totalShopNum": 297
    }

### 요청
개발 노드가 많지 않다면, tagId만 입력하도록 변경하는 것이 가장 좋은 방향입니다.
그렇지 않다면 현재 방식에서 bug를 확인하고 수정하는 방향으로 요청드립니다.

**Comment by akalswl14** [comment]
@loiu87 해당 사항 수정하여 issue/46 브랜치에 적용 시켜놓았습니다. 제가 154번 태그로 조회한 결과와 데이터베이스를 통해 직접 찾아본 결과가 모두 totalShopNum이 38개로 조회되는데 이점에서 문제가 있는지 확인 부탁드립니다.
