### ISSUE TITLE
APP API  이벤트 리스트에서 totalEventNum 버그

### ISSUE THREAD

**Issue by aeuna** [akalswl14/stylebox_server#7]
- [x] 이벤트 모두가 isOnList false 인 경우, filter 가 d-day 인 경우 null 반환되는 버그 발생

**Comment by akalswl14** [comment]
김지완 대표님 컨펌 후에 앱 API 서버에 반영해야함. 반영 여부 확인을 위해 반영 후에 이슈 클로즈 할예정.
